In [2]:
import pandas as pd
import glob

In [5]:
files = glob.glob('../dados/selected/*.csv')
files

['../dados/selected/2018-05-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-04-26_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-11-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-09-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-10-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-07-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-03-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-12-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-04-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-09-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-12-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-08-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-06-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-03-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-10-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-02-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-11-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-08-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-04-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-02-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2017-01-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-06-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-01-01_156_-_Base_de_Dados.csv',
 '../dados/selected/2018-07-01_156_-_Base_de_Dados.csv']

In [14]:
df = pd.read_csv(files[0], sep=';', encoding="latin1", on_bad_lines="skip")

for file in files[1:]:
    try:
        df_temp = pd.read_csv(file, sep=';', encoding="latin1",  on_bad_lines="skip")
    except Exception as e:
        print(f"Erro ao ler o arquivo {file}: {e}")
        continue
    df = pd.concat([df, df_temp], ignore_index=True)

df

/tmp/ipykernel_31888/3556696225.py:5: DtypeWarning: Columns (0: SOLICITACAO) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(file, sep=';', encoding="latin1",  on_bad_lines="skip")

Erro ao ler o arquivo ../dados/selected/2018-02-01_156_-_Base_de_Dados.csv: No columns to parse from file

,SOLICITACAO,TIPO,ORGAO,DATA,HORARIO,ASSUNTO,SUBDIVISAO,DESCRICAO,LOGRADOURO_ASS,BAIRRO_ASS,REGIONAL_ASS,MEIO_RESPOSTA,OBSERVACAO,SEXO,BAIRRO_CIDADAO,REGIONAL_CIDADAO,DATA_NASC,TIPO_CIDADAO,ORGAO_RESP,RESPOSTA_FINAL
0,---------------------,-------,------------,--------,---------------,---------------,-------------------,---------------------,-------------------------------,---------------------,-------------------------,---------------------------,-----------------------,---------,----------------------------,---------------------------------,-------------------,-----------------------,-----------------------,----------------------------
1,7288459,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,06/04/2018,10:02:19,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"DESEMBARGADOR MOTTA, 1070",AGUA VERDE,Unidade Regional Portao,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão
2,NaN,Informamos que encaminhamos a viatura 418 às 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7308990,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,20/04/2018,06:43:11,TRÂNSITO,FISCALIZAÇÃO IMEDIATA,"SOLICITA AGENTES PARA ORIENTAÇÃO DE TRÂNSITO, ...","VISCONDE DE GUARAPUAVA, 0",CENTRO,Unidade Regional Matriz,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão
4,NaN,"Informamos que encaminhamos a viatura 236, às ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263853,NaN,Realizamos fiscalização no dia 07/06/2018 às 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263854,7375373,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,13/06/2018,18:30:36,TRÂNSITO,SOLICITA FISCALIZAÇÃO PROGRAMADA,SOLICITA A FISCALIZAÇÃO PROGRAMADA PRÓXIMO AO ...,"PADRE ANTONIO, 33",ALTO DA GLORIA,Unidade Regional Matriz,EMAIL,(REGISTRADO VIA CHAT),M,PLANTA BAIRRO WEISSOPOLIS ...,NaN,23/10/1973,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão
263855,NaN,Realizamos fiscalização no dia 15/06/2018 às 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263856,7370469,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,09/06/2018,15:59:57,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"VISCONDE DE GUARAPUAVA, 2798",CENTRO,Unidade Regional Matriz,TELEFONE,EM FRENTE AO NÚMERO. NÃO SOUBE INFORMAR PONTO ...,M,IPE ...,NaN,24/04/1993,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão
263857,NaN,Informamos que o atendimento aos pedidos para ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.columns

Index(['SOLICITACAO', 'TIPO', 'ORGAO', 'DATA', 'HORARIO', 'ASSUNTO',
       'SUBDIVISAO', 'DESCRICAO', 'LOGRADOURO_ASS', 'BAIRRO_ASS',
       'REGIONAL_ASS', 'MEIO_RESPOSTA', 'OBSERVACAO', 'SEXO', 'BAIRRO_CIDADAO',
       'REGIONAL_CIDADAO', 'DATA_NASC', 'TIPO_CIDADAO', 'ORGAO_RESP',
       'RESPOSTA_FINAL'],
      dtype='str')

In [ ]:
import numpy as np

df['MENSAGEM_RESPOSTA'] = df['TIPO'].shift(-1)

next_row_is_broken = df['SOLICITACAO'].shift(-1).isna()
df.loc[~next_row_is_broken, 'MENSAGEM_RESPOSTA'] = np.nan

df_clean = df.dropna(subset=['SOLICITACAO']).copy()

df_clean = df_clean[df_clean['SOLICITACAO'] != '---------------------'].reset_index(drop=True)

df_clean

,SOLICITACAO,TIPO,ORGAO,DATA,HORARIO,ASSUNTO,SUBDIVISAO,DESCRICAO,LOGRADOURO_ASS,BAIRRO_ASS,...,MEIO_RESPOSTA,OBSERVACAO,SEXO,BAIRRO_CIDADAO,REGIONAL_CIDADAO,DATA_NASC,TIPO_CIDADAO,ORGAO_RESP,RESPOSTA_FINAL,MENSAGEM_RESPOSTA
0,7288459,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,06/04/2018,10:02:19,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"DESEMBARGADOR MOTTA, 1070",AGUA VERDE,...,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que encaminhamos a viatura 418 às 1...
1,7308990,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,20/04/2018,06:43:11,TRÂNSITO,FISCALIZAÇÃO IMEDIATA,"SOLICITA AGENTES PARA ORIENTAÇÃO DE TRÂNSITO, ...","VISCONDE DE GUARAPUAVA, 0",CENTRO,...,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Informamos que encaminhamos a viatura 236, às ..."
2,7317294,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,25/04/2018,15:09:52,TRÂNSITO,FISCALIZAÇÃO IMEDIATA,SOLICITA FISCALIZAÇÃO DE TRÂNSITO DEVIDO A ACI...,"BRIGADEIRO FRANCO, 508",MERCES,...,NENHUM,508,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Em resposta à solicitação, informamos que enca..."
3,7304754,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,17/04/2018,19:17:30,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"GENERAL CARNEIRO, 181",ALTO DA GLORIA,...,NENHUM,NaN,M,NaN,NaN,22/08/1966,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Informamos que encaminhamos a viatura 249, che..."
4,7304871,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,17/04/2018,21:01:17,TRÂNSITO,VEÍCULO ESTACIONADO - GUIA REBAIXADA,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"IVO LEÃO, 205",ALTO DA GLORIA,...,TELEFONE,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Informamos que encaminhamos a viatura 243, che..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238608,7362317,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,02/06/2018,02:28:54,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"VICENTE MACHADO, 900",BATEL,...,EMAIL,NaN,M,VILA PROGRESSO ...,NaN,26/11/1965,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que encaminhamos ao local a viatura...
238609,7365563,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,05/06/2018,17:07:41,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"REPÚBLICA ARGENTINA, 0",NOVO MUNDO,...,TELEFONE,NÃO SOUBE INFORMAR A NUMERAÇÃO PREDIAL E A TRA...,M,VILA PROGRESSO ...,NaN,08/12/1975,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que o atendimento aos pedidos para ...
238610,7365564,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,05/06/2018,17:07:41,TRÂNSITO,SOLICITA FISCALIZAÇÃO PROGRAMADA,SOLICITA FISCALIZAÇÃO DEVIDO UMA DUSTER BRANCA...,"WINSTON CHURCHILL, 2657",PINHEIRINHO,...,TELEFONE,NaN,M,VILA PROGRESSO ...,NaN,08/12/1975,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Realizamos fiscalização no dia 07/06/2018 às 1...
238611,7375373,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,13/06/2018,18:30:36,TRÂNSITO,SOLICITA FISCALIZAÇÃO PROGRAMADA,SOLICITA A FISCALIZAÇÃO PROGRAMADA PRÓXIMO AO ...,"PADRE ANTONIO, 33",ALTO DA GLORIA,...,EMAIL,(REGISTRADO VIA CHAT),M,PLANTA BAIRRO WEISSOPOLIS ...,NaN,23/10/1973,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Realizamos fiscalização no dia 15/06/2018 às 1...
238612,7370469,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,09/06/2018,15:59:57,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"VISCONDE DE GUARAPUAVA, 2798",CENTRO,...,TELEFONE,EM FRENTE AO NÚMERO. NÃO SOUBE INFORMAR PONTO ...,M,IPE ...,NaN,24/04/1993,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que o atendimento aos pedidos para ...

In [19]:
df_clean[df_clean["SOLICITACAO"] == "7288459"]

,SOLICITACAO,TIPO,ORGAO,DATA,HORARIO,ASSUNTO,SUBDIVISAO,DESCRICAO,LOGRADOURO_ASS,BAIRRO_ASS,...,MEIO_RESPOSTA,OBSERVACAO,SEXO,BAIRRO_CIDADAO,REGIONAL_CIDADAO,DATA_NASC,TIPO_CIDADAO,ORGAO_RESP,RESPOSTA_FINAL,MENSAGEM_RESPOSTA
0,7288459,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,06/04/2018,10:02:19,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"DESEMBARGADOR MOTTA, 1070",AGUA VERDE,...,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que encaminhamos a viatura 418 às 1...
4087,7288459,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,06/04/2018,10:02:19,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"DESEMBARGADOR MOTTA, 1070",AGUA VERDE,...,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que encaminhamos a viatura 418 às 1...

In [20]:
df_clean_no_dups = df_clean.drop_duplicates(subset=['SOLICITACAO', "DATA", "HORARIO"], keep='first').reset_index(drop=True)
df_clean_no_dups

,SOLICITACAO,TIPO,ORGAO,DATA,HORARIO,ASSUNTO,SUBDIVISAO,DESCRICAO,LOGRADOURO_ASS,BAIRRO_ASS,...,MEIO_RESPOSTA,OBSERVACAO,SEXO,BAIRRO_CIDADAO,REGIONAL_CIDADAO,DATA_NASC,TIPO_CIDADAO,ORGAO_RESP,RESPOSTA_FINAL,MENSAGEM_RESPOSTA
0,7288459,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,06/04/2018,10:02:19,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"DESEMBARGADOR MOTTA, 1070",AGUA VERDE,...,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que encaminhamos a viatura 418 às 1...
1,7308990,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,20/04/2018,06:43:11,TRÂNSITO,FISCALIZAÇÃO IMEDIATA,"SOLICITA AGENTES PARA ORIENTAÇÃO DE TRÂNSITO, ...","VISCONDE DE GUARAPUAVA, 0",CENTRO,...,NENHUM,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Informamos que encaminhamos a viatura 236, às ..."
2,7317294,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,25/04/2018,15:09:52,TRÂNSITO,FISCALIZAÇÃO IMEDIATA,SOLICITA FISCALIZAÇÃO DE TRÂNSITO DEVIDO A ACI...,"BRIGADEIRO FRANCO, 508",MERCES,...,NENHUM,508,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Em resposta à solicitação, informamos que enca..."
3,7304754,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,17/04/2018,19:17:30,TRÂNSITO,VEÍCULO ESTACIONADO EM HORÁRIO/LOCAL PROIBIDO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"GENERAL CARNEIRO, 181",ALTO DA GLORIA,...,NENHUM,NaN,M,NaN,NaN,22/08/1966,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Informamos que encaminhamos a viatura 249, che..."
4,7304871,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,17/04/2018,21:01:17,TRÂNSITO,VEÍCULO ESTACIONADO - GUIA REBAIXADA,SOLICITA FISCALIZAÇÃO DE TRÂNSITO EM VIRTUDE D...,"IVO LEÃO, 205",ALTO DA GLORIA,...,TELEFONE,NaN,M,NaN,NaN,,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,"Informamos que encaminhamos a viatura 243, che..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146089,7362317,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,02/06/2018,02:28:54,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"VICENTE MACHADO, 900",BATEL,...,EMAIL,NaN,M,VILA PROGRESSO ...,NaN,26/11/1965,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que encaminhamos ao local a viatura...
146090,7365563,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,05/06/2018,17:07:41,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"REPÚBLICA ARGENTINA, 0",NOVO MUNDO,...,TELEFONE,NÃO SOUBE INFORMAR A NUMERAÇÃO PREDIAL E A TRA...,M,VILA PROGRESSO ...,NaN,08/12/1975,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que o atendimento aos pedidos para ...
146091,7365564,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,05/06/2018,17:07:41,TRÂNSITO,SOLICITA FISCALIZAÇÃO PROGRAMADA,SOLICITA FISCALIZAÇÃO DEVIDO UMA DUSTER BRANCA...,"WINSTON CHURCHILL, 2657",PINHEIRINHO,...,TELEFONE,NaN,M,VILA PROGRESSO ...,NaN,08/12/1975,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Realizamos fiscalização no dia 07/06/2018 às 1...
146092,7375373,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,13/06/2018,18:30:36,TRÂNSITO,SOLICITA FISCALIZAÇÃO PROGRAMADA,SOLICITA A FISCALIZAÇÃO PROGRAMADA PRÓXIMO AO ...,"PADRE ANTONIO, 33",ALTO DA GLORIA,...,EMAIL,(REGISTRADO VIA CHAT),M,PLANTA BAIRRO WEISSOPOLIS ...,NaN,23/10/1973,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Realizamos fiscalização no dia 15/06/2018 às 1...
146093,7370469,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,09/06/2018,15:59:57,TRÂNSITO,FISCALIZAÇÃO,SOLICITA FISCALIZAÇÃO DE TRÂNSITO.,"VISCONDE DE GUARAPUAVA, 2798",CENTRO,...,TELEFONE,EM FRENTE AO NÚMERO. NÃO SOUBE INFORMAR PONTO ...,M,IPE ...,NaN,24/04/1993,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Retirada da Pendência de Revisão,Informamos que o atendimento aos pedidos para ...